# Site settings
title: "Khaled Ahmed Website"
description: "Welcome to SkillSetSaga, a digital chronicle of my ongoing journey to mastery. Within these virtual pages, you'll uncover a dynamic record of my career progression, skill acquisition, and professional accomplishments. As I navigate through diverse roles and tackle new challenges, each entry represents a chapter in my relentless pursuit of expertise. From technical proficiencies to soft skills, from project triumphs to leadership milestones, SkillSetSaga invites you to witness the evolution of my abilities and the dedication I bring to refining them. Join me on this saga of self-improvement, where growth is not just a destination but a continuous expedition towards excellence."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Khaled Ahmed"
resume_title:                   "Software Engineering Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "khahmed2143@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "929-343-1970"
resume_contact_address:         "1919 McGraw Avenue, Bronx"

resume_header_contact_info:     "1919 McGraw Avenue, Bronx • 929-343-1970 • khahmed2143@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>As a passionate software engineering student at Queens College, I am dedicated to honing my skills in programming and technology. My journey has been shaped by a rigorous curriculum encompassing diverse subjects such as data structures, algorithms, and software engineering. With hands-on experience in projects ranging from game development to data analysis, I am excited to contribute my knowledge and creativity to innovative solutions. Looking ahead, my immediate career goal is to secure internships expanding my expertise and paving the way for a successful future in software engineering.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Khaled2143"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/khaled-ahmed1/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
